version: '3.8'
services:
  db:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  backend:
    build: ./backend/
    restart: always
    environment:
      DATABASE_URL: mysql://root:p@ssword@db/mydb
      JWT_SECRET: "jsonwebtokensecret"
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend/
    restart: always
    environment:
      API_URL: http://localhost:3000
      GOOGLE_MAP_API_KEY: your_google_map_api_key
    ports:
      - "8080:8080"
    depends_on:
      - backend
