version: '3.8'
services:
  db:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  backend:
    build: ./backend/
    restart: always
    environment:
      DATABASE_URL: mysql://root:p@ssword@db/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db
