version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql